# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import transfer_pb2 as proto_dot_transfer__pb2


class FileTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transfer = channel.stream_stream(
                '/FileTransfer/Transfer',
                request_serializer=proto_dot_transfer__pb2.TransferReq.SerializeToString,
                response_deserializer=proto_dot_transfer__pb2.TransferResp.FromString,
                )


class FileTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transfer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transfer': grpc.stream_stream_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=proto_dot_transfer__pb2.TransferReq.FromString,
                    response_serializer=proto_dot_transfer__pb2.TransferResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transfer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/FileTransfer/Transfer',
            proto_dot_transfer__pb2.TransferReq.SerializeToString,
            proto_dot_transfer__pb2.TransferResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
