# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/transfer.proto\"\r\n\x0bTransferReq\"\x0e\n\x0cTransferResp2=\n\x0c\x46ileTransfer\x12-\n\x08Transfer\x12\x0c.TransferReq\x1a\r.TransferResp\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.transfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TRANSFERREQ']._serialized_start=24
  _globals['_TRANSFERREQ']._serialized_end=37
  _globals['_TRANSFERRESP']._serialized_start=39
  _globals['_TRANSFERRESP']._serialized_end=53
  _globals['_FILETRANSFER']._serialized_start=55
  _globals['_FILETRANSFER']._serialized_end=116
# @@protoc_insertion_point(module_scope)
